language: android
jdk: oraclejdk7
android:
    components:
        - platform-tools
        - tools
        - build-tools-24.0.0
        - android-24
        - sys-img-armeabi-v7a-android-22
        - sys-img-x86-android-17
before_install:
    - chmod +x gradlew